### ISSUE TITLE
Improve/finish Windows support

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/abb_robot_driver#21]
While the driver can be used on Windows, there are a few rough edges which we need to address before we can state Windows is fully supported.

This issue will track all outstanding tasks and identified problems with the packages on Windows.

Todo:

 - [ ] #3: add Windows CI
 - [ ] #4: add build documentation for Windows (related: #17)
 - [ ] #17: `abb_egm_hardware_interface` build failing due to `robot_hw.h` collisions with `windows.h`
 - [ ] #20: multi-line `rosservice` invocations not working in `cmd.exe`

**Comment by gavanderhoorn** [comment]
That's ok. I was just wondering whether he'd already forked to somewhere and wanted to take a look.

**Comment by ooeygui** [comment]
@gavanderhoorn I'm sorry, I do not have any status. Our priority queue grows significantly faster than we can whittle it down. If you can share data about the customer impact on this, it might help make the case to increase the priority in our backlog.

**Comment by gavanderhoorn** [comment]
@ooeygui @lilustga were you able to improve anything in the end?

**Comment by ooeygui** [comment]
@gavanderhoorn Thanks for the ping. We are not currently working on this due to resource constraints.

**Comment by gavanderhoorn** [comment]
Ok. Thanks for the update.
